##PRODUCTION
GET https://cse341-project1-77sy.onrender.com/Users

# Get Contact by Id localhost

GET https://localhost:3000/users/666e39d09ddd74b56a62b4bb

#Create Contact

POST https://localhost:3000/users/ HTTP/1.1

content-type: application/json

